### ISSUE TITLE
https://api.nanit.com/login/ broken

### ISSUE THREAD

**Issue by FullerNgs** [indiefan/home_assistant_nanit#8] opened 2023-12-21 00:57 UTC
Hi,

The api site is not responding. How are we pulling the tokens?

**Comment by indiefan** [comment] 2024-01-21 22:14
Are you still experiencing this issue? I'm unable to reproduce so I'm going to close this (maybe just an outage on their end?). If you're still running into it, feel free to reopen and we can try to figure out how I can repro.

**Closed by indiefan** 2024-01-21 22:14 UTC
